import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import 'tailwindcss/tailwind.css'
import Banner from '../components/Banner'
import Header from '../components/Header'
import ProductFeed from '../components/ProductFeed'
import { useDispatch } from 'react-redux'
import { addToBasket } from "../slices/basketReducer";
import { db } from '../firebase'
import { useSession } from 'next-auth/client'



export default function Home({products}) {
  const dispatch = useDispatch()
  const [session] = useSession()


  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className='max-w-screen-2xl mx-auto'>
        <Banner />
        <ProductFeed products={products} />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const products = await fetch('https://amz-next.vercel.app/api/products')
  .then(
    (res)=> res.json()
  );

  return {
    props: {
      products
    }
  }
}